# Generated by Django 4.0.4 on 2022-04-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1028, verbose_name='Название камеры')),
            ],
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.TextField(blank=True, null=True, verbose_name='Статистика')),
                ('video', models.FileField(upload_to='media/videos/%Y/%m/%d/', verbose_name='Видео')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera', verbose_name='Камера')),
            ],
        ),
    ]
