# Generated by Django 4.0.4 on 2022-04-24 08:06

from django.db import migrations, models
import mixins.validators


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreport',
            name='report_xlsx',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Отчёт в формате xlsx'),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', validators=[mixins.validators.validate_file_extension], verbose_name='Видео'),
        ),
    ]
