version: '3'

services:
  db:
    image: postgres:12.0-alpine
    container_name: camera-sound-db
    env_file: .env
    ports:
      - 5432:5432
  web:
    image: python:3.9
    depends_on:
      - db
    volumes:
      - .:/opt/camera_sound
    container_name: camera-sound-web
    ports:
      - 8000:8000
    env_file: .env
    working_dir: /opt/camera_sound
    command: /bin/bash -c "scripts/run-server.sh"